# Generated by Django 4.1.1 on 2022-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.IntegerField(verbose_name='property')),
                ('building_id', models.IntegerField(verbose_name='building_id')),
                ('owner_acquisition_date', models.DateTimeField(max_length=64, verbose_name='owner_date')),
                ('street1', models.CharField(max_length=64, verbose_name='street')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('zip', models.IntegerField(verbose_name='zip')),
                ('last_name', models.CharField(max_length=64, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('email', models.EmailField(max_length=64, verbose_name='email')),
                ('floor', models.IntegerField(blank=True, verbose_name='floor')),
                ('surface', models.IntegerField(blank=True, verbose_name='surface')),
            ],
        ),
    ]
