# Generated by Django 4.1.1 on 2022-10-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.IntegerField(default='0', verbose_name='floor'),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface',
            field=models.IntegerField(default='0', verbose_name='surface'),
        ),
    ]
